package com.example.worklink.worker;

import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Typeface;
import android.graphics.pdf.PdfDocument;
import android.os.Environment;
import android.widget.Toast;

import com.example.worklink.DBHelper;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Locale;

public class ResumeBuilder {

    private Context context;
    private DBHelper dbHelper;

    public ResumeBuilder(Context context) {
        this.context = context;
        this.dbHelper = new DBHelper(context);
    }

    public File generateResume(int workerId) {
        SQLiteDatabase db = dbHelper.getReadableDatabase();
        Cursor cursor = db.rawQuery(
                "SELECT u.name, u.phone, w.skills, w.experience, w.rating " +
                "FROM users u JOIN worker_profile w ON u.id = w.worker_id " +
                "WHERE u.id = ?", new String[]{String.valueOf(workerId)});

        File file = null;
        if (cursor.moveToFirst()) {
            String name = cursor.getString(0);
            String phone = cursor.getString(1);
            String skills = cursor.getString(2);
            int experience = cursor.getInt(3);
            double rating = cursor.getDouble(4);

            file = createPdf(name, phone, skills, experience, rating);
        } else {
            Toast.makeText(context, "Worker data not found", Toast.LENGTH_SHORT).show();
        }
        cursor.close();
        return file;
    }

    private File createPdf(String name, String phone, String skills, int experience, double rating) {
        PdfDocument pdfDocument = new PdfDocument();
        Paint paint = new Paint();
        Paint titlePaint = new Paint();

        PdfDocument.PageInfo pageInfo = new PdfDocument.PageInfo.Builder(595, 842, 1).create();
        PdfDocument.Page page = pdfDocument.startPage(pageInfo);
        Canvas canvas = page.getCanvas();

        // Title
        titlePaint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        titlePaint.setTextSize(24);
        titlePaint.setColor(Color.BLUE);
        canvas.drawText("WORKLINK RESUME", 180, 50, titlePaint);

        // Name
        paint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        paint.setTextSize(18);
        canvas.drawText("Name: " + name, 50, 100, paint);

        // Contact
        paint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.NORMAL));
        paint.setTextSize(14);
        canvas.drawText("Contact: " + phone, 50, 130, paint);

        // Experience
        canvas.drawText("Experience: " + experience + " years", 50, 160, paint);

        // Rating (Formatted to 2 decimal places)
        String ratingStr = String.format(Locale.US, "%.2f", rating);
        canvas.drawText("Overall Rating: " + ratingStr + " / 5.0", 50, 190, paint);

        // Skills Header
        paint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        canvas.drawText("Skills:", 50, 240, paint);

        // Skills List (Simple wrapping logic)
        paint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.NORMAL));
        String[] skillArray = skills.split(",");
        int y = 270;
        for (String skill : skillArray) {
            canvas.drawText("• " + skill.trim(), 70, y, paint);
            y += 25;
        }

        // Footer
        paint.setTextSize(10);
        paint.setColor(Color.GRAY);
        canvas.drawText("Generated by WorkLink App", 220, 800, paint);

        pdfDocument.finishPage(page);

        // Save file
        File file = new File(context.getExternalFilesDir(null), name.replace(" ", "_") + "_Resume.pdf");

        try {
            pdfDocument.writeTo(new FileOutputStream(file));
        } catch (IOException e) {
            e.printStackTrace();
            Toast.makeText(context, "Error generating PDF: " + e.getMessage(), Toast.LENGTH_SHORT).show();
            return null;
        } finally {
            pdfDocument.close();
        }

        return file;
    }
}
