package com.example.worklink.worker;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Typeface;
import android.graphics.pdf.PdfDocument;
import android.widget.Toast;
import com.example.worklink.api.models.WorkerStatsResponse;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Locale;

public class ResumeBuilder {

    private Context context;
    public ResumeBuilder(Context context) {
        this.context = context;
    }
    public File generateResume(WorkerStatsResponse stats) {
        if (stats == null || stats.getUser() == null || stats.getProfile() == null) {
            Toast.makeText(context, "Worker data missing", Toast.LENGTH_SHORT).show();
            return null;
        }

        String name = stats.getUser().getName();
        String email = stats.getUser().getEmail();
        String skills = stats.getProfile().getSkills() != null ? String.join(", ", stats.getProfile().getSkills()) : "None";
        int experience = stats.getProfile().getExperience() != null ? stats.getProfile().getExperience() : 0;
        double rating = stats.getProfile().getRating() != null ? stats.getProfile().getRating() : 0.0;

        return createPdf(name, email, skills, experience, rating);
    }

    private File createPdf(String name, String email, String skills, int experience, double rating) {
        PdfDocument pdfDocument = new PdfDocument();
        Paint paint = new Paint();
        Paint titlePaint = new Paint();

        PdfDocument.PageInfo pageInfo = new PdfDocument.PageInfo.Builder(595, 842, 1).create();
        PdfDocument.Page page = pdfDocument.startPage(pageInfo);
        Canvas canvas = page.getCanvas();

        // Title
        titlePaint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        titlePaint.setTextSize(24);
        titlePaint.setColor(Color.BLUE);
        canvas.drawText("WORKLINK RESUME", 180, 50, titlePaint);

        // Name
        paint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        paint.setTextSize(18);
        canvas.drawText("Name: " + name, 50, 100, paint);

        // Email
        paint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.NORMAL));
        paint.setTextSize(14);
        canvas.drawText("Email: " + email, 50, 130, paint);

        // Experience
        canvas.drawText("Experience: " + experience + " years", 50, 160, paint);

        // Rating
        String ratingStr = String.format(Locale.US, "%.2f", rating);
        canvas.drawText("Overall Rating: " + ratingStr + " / 5.0", 50, 190, paint);

        // Skills Header
        paint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        canvas.drawText("Skills:", 50, 240, paint);

        // Skills List
        paint.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.NORMAL));
        String[] skillArray = skills.split(",");
        int y = 270;
        for (String skill : skillArray) {
            canvas.drawText("• " + skill.trim(), 70, y, paint);
            y += 25;
        }

        // Footer
        paint.setTextSize(10);
        paint.setColor(Color.GRAY);
        canvas.drawText("Generated by WorkLink App", 220, 800, paint);

        pdfDocument.finishPage(page);

        File file = new File(context.getExternalFilesDir(null), name.replace(" ", "_") + "_Resume.pdf");

        try {
            pdfDocument.writeTo(new FileOutputStream(file));
        } catch (IOException e) {
            e.printStackTrace();
            Toast.makeText(context, "Error generating PDF: " + e.getMessage(), Toast.LENGTH_SHORT).show();
            return null;
        } finally {
            pdfDocument.close();
        }

        return file;
    }
}
